FROM apache/airflow:2.8.1
USER root
RUN apt-get update && apt-get install -y openjdk-17-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
USER airflow
RUN pip install pyarrow pyspark azure-storage-file-datalake azure-storage-blob pandas